### ISSUE TITLE
ENV support?

### ISSUE THREAD

**Issue by stephanbuys** [ghmlee/rust-docker#38]
Hi,

Does your library support the main DOCKER_HOST and DOCKER_CERT_PATH environment variables if available?

Regards,
Stephan

**Comment by ghmlee** [comment]
@stephanbuys It is not difficult to support those two environment variables. However, isn't it better that developers using this library should explicitly write the code like below?

``` rust
extern crate docker;

use docker::Docker;
use std::path::Path;

fn main() {
    let key = Path::new("/Users/<username>/.docker/machine/certs/key.pem");
    let cert = Path::new("/Users/<username>/.docker/machine/certs/cert.pem");
    let ca = Path::new("/Users/<username>/.docker/machine/certs/ca.pem");

    let mut docker = match Docker::connect("tcp://192.168.99.100:2376") {
        Ok(docker) => docker,
        Err(e) => { panic!("{}", e); }
    };
    docker.set_tls(&key, &cert, &ca).unwrap();
}
```

**Comment by ghmlee** [comment]
@stephanbuys I will update the environment variables for Mac users.

**Comment by stephanbuys** [comment]
@ghmlee I would basically just write the code to pull/build those settings from the environment and then invoke the library. I think that these days (with docker-machine, docker-compose, etc), the goto/intuitive way is to rely on those environment variables being set. I guess its up to you if you want to have to deal with it your library, or have developers deal with it.

One of the challenges is that there are a lot of variations on the core environment variables used by docker, so I would almost expect it to be more stable if implemented properly within the library.

**Comment by tobz** [comment]
What about a helper method?  That way, people who want the fine-grained control can use the `connect...` stuff by hand, and others can use a convenience method... maybe something like `connect_local`.  The convenience method could look for the appropriate environment variables or Unix socket according to the way docker-machine/docker work by default.
