### ISSUE TITLE
Responses truncated

### ISSUE THREAD

**Issue by stephanbuys** [ghmlee/rust-docker#39]
I've noticed that sometime the responses from the daemon are truncated (when you have a large amount of containers running). Perhaps using something like hyper would be a good option to handle the docker daemon communication?

**Comment by stephanbuys** [comment]
@ghmlee Could I add some more debug info, etc to assist with debugging/solving this? I'm still absolutely new to rust, but would be willing to try

**Comment by ghmlee** [comment]
@stephanbuys Sure, it will be helpful.

**Comment by stephanbuys** [comment]
@ghmlee, ok disclaimer, I'm new to rust and a fair developer at best. Where I've gotten to is adding a `debug` line to `line 103` in `src/docker.rs`, namely 

```

        let body = try!(response.get_encoded_body());
        println!("Decoding... {}", body );

```

I can clearly see that the output JSON from the body is truncated after 3289 bytes, this then leads to the next line the `decoding` step panicking with:

```
thread '<main>' panicked at 'decoder error', src/main.rs:34
```

I'm a little bit out of my depth but I think the issue is in how the tcp stream is handled during the response from the server. I have a whole lot of containers.

**Comment by tobz** [comment]
I actually wrote a PR to switch to Hyper! #41 if you're interested.  It changes the API so it wouldn't be a drop in, but see if it fixes your issue?
