### ISSUE TITLE
Is rust-docker still maintained?

### ISSUE THREAD

**Issue by emk** [ghmlee/rust-docker#43]
Hello! This looks like a really great crate, and I'd love to use it to enable [cage](http://blog.faraday.io/announcing-cage-develop-and-deploy-complex-docker-applications/) to talk to the Docker daemon. If this crate is still maintained, I'd be happy to send PRs for:
- Support for Docker 1.12 .
- Support for basic Windows builds.
- Support for connecting using the default `DOCKER_HOST` and related environment variables, so neither the application nor the user needs to do any special configuration.

Thank you for any information you can provide!

**Comment by kpcyrd** [comment]
In case anybody else runs over this issue, I've started using the [boondock] fork instead.

[boondock]: https://crates.io/crates/boondock
